version: "3.9"

services:
  web:
    image: httpd:latest
    ports:
      - '8080:80'
    volumes:
      - ./site/:/usr/local/apache2/htdocs
    networks:
      - netweb

networks:
   netweb:
     driver: bridge
